sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t cohenpts/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cohenpts/docker-react yarn test


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-400070906403"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET
