sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t cohenpts/docker-react -f Dockerfile.dev .

  script:
  - docker run -e CI=true cohenpts/docker-react yarn test
